# Generated by Django 5.2 on 2025-04-07 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=100)),
                ('otp_secret', models.CharField(max_length=200)),
                ('otp_fld', models.CharField(max_length=70)),
                ('is_blocked', models.BooleanField(default=False)),
            ],
        ),
    ]
